# Generated by Django 4.1.2 on 2022-11-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=255)),
                ('Lastname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password1', models.CharField(max_length=255)),
                ('Password2', models.CharField(max_length=255)),
            ],
        ),
    ]
